export const BUBBLES_ACTION_SET_HOVER = 'BUBBLES_ACTION_SET_HOVER';
export const BUBBLES_ACTION_MOVE_ARTICLE_TO_ARCHIVE = 'BUBBLES_ACTION_MOVE_ARTICLE_TO_ARCHIVE';
export const BUBBLES_ACTION_TOGGLE_DRAWER = 'BUBBLES_ACTION_TOGGLE_DRAWER';
